use crate::domain::models::{
    ApprovalDecision, NoticeLevel, PermissionMode, StreamChunk, ToolResult,
};

/// Domain-level application events flowing through the event loop.
/// crossterm types MUST NOT appear here — the adapter converts them to DomainInputEvent.
#[allow(dead_code)]
#[derive(Debug)]
pub enum AppEvent {
    /// Converted terminal input (crossterm → domain)
    InputEvent(DomainInputEvent),
    /// Streaming chunk from provider
    ProviderChunk(StreamChunk),
    /// Tool execution result
    ToolResult(ToolResultEvent),
    /// Terminal resize
    Resize(u16, u16),
    /// Render tick
    Tick,
    /// Graceful shutdown request
    Shutdown,
    /// System notice (status bar messages)
    SystemNotice(NoticeLevel, String),
    /// Internal domain events (legacy — kept for backward compat with 1.1a event loop)
    DomainEvent(DomainEventPayload),
    /// Permission request from SecurityAdapter — TUI displays PermissionCard, user responds via oneshot.
    PermissionRequest {
        tool_name: String,
        tool_input: serde_json::Value,
        response_tx: tokio::sync::oneshot::Sender<ApprovalDecision>,
    },
    /// Change the active permission mode.
    SetPermissionMode(PermissionMode),
    /// Retry a message after backoff delay has elapsed.
    RetryMessage(String),
    /// Title generated by background task.
    TitleGenerated { title: String },
    /// AskUserQuestion tool call — display question card and send answer via oneshot.
    AskUserQuestion {
        tool_use_id: String,
        question: String,
        response_tx: tokio::sync::oneshot::Sender<String>,
    },
    /// Crash recovery prompt — display recovery FeedbackBlock on startup.
    RecoveryPrompt { title: String, token_count: u32 },
}

/// Event wrapping a tool execution result.
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct ToolResultEvent {
    pub tab_id: String,
    pub result: ToolResult,
}

/// Terminal input events, abstracted from crossterm.
/// The TUI adapter converts `crossterm::event::Event` into these.
#[derive(Debug, Clone)]
pub enum DomainInputEvent {
    KeyPress(char),
    SpecialKey(DomainKey),
    Resize(u16, u16),
    FocusGained,
    FocusLost,
    /// Raw image bytes pasted from clipboard (already decoded from base64 if applicable).
    // Covers: FR112
    ImagePaste(Vec<u8>),
    /// Plain text pasted from clipboard (bracketed paste mode).
    Paste(String),
}

/// Abstract key representation — no crossterm dependency.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DomainKey {
    Enter,
    ShiftEnter,
    CtrlEnter,
    /// Alt+Enter: insert newline (VS Code terminal alternative to Shift+Enter).
    // Covers: Sprint Change Proposal 2026-04-08, UX-DR76 amendment
    AltEnter,
    /// Alt+M: toggle multi-line mode (VS Code terminal alternative to Ctrl+E).
    // Covers: Sprint Change Proposal 2026-04-08, UX-DR76 amendment
    AltM,
    Esc,
    Backspace,
    Delete,
    Up,
    Down,
    Left,
    Right,
    Home,
    End,
    Tab,
    ShiftTab,
    CtrlC,
    CtrlE,
    CtrlP,
    CtrlR,
    CtrlX,
}

/// Payload for domain-originated events (placeholder for future stories).
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub enum DomainEventPayload {
    /// Placeholder — streaming events, tool results, etc. added in later stories
    Noop,
}

/// Action returned by apply_chunk() to tell the event loop what to do.
#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ChunkAction {
    /// No action needed.
    None,
    /// Trigger a redraw on next tick.
    NeedsRedraw,
    /// Turn is complete — persist and optionally generate title.
    TurnComplete {
        persist: bool,
        trigger_title_generation: bool,
    },
    /// Turn continues (tool use loop).
    TurnContinuing,
}
