use crate::domain::models::tab::ConversationId;
use crate::domain::models::view_state::ScrollDelta;
use crate::domain::models::{
    NoticeLevel, PermissionMode, SkillTrustResponse, StreamChunk, ToolResult,
};
use crate::domain::services::cross_search::CrossSearchResult;

/// Domain-level application events flowing through the event loop.
/// crossterm types MUST NOT appear here — the adapter converts them to DomainInputEvent.
#[allow(dead_code)]
#[derive(Debug)]
pub enum AppEvent {
    /// Converted terminal input (crossterm → domain)
    InputEvent(DomainInputEvent),
    /// Streaming chunk from provider
    ProviderChunk {
        conversation_id: ConversationId,
        chunk: StreamChunk,
    },
    /// Tool execution result
    ToolResult(ToolResultEvent),
    /// Terminal resize
    Resize(u16, u16),
    /// Render tick
    Tick,
    /// Graceful shutdown request
    Shutdown,
    /// System notice (status bar messages).
    /// `conversation_id` routes the notice to a specific tab; `None` = global (show always).
    SystemNotice {
        conversation_id: Option<ConversationId>,
        level: NoticeLevel,
        message: String,
    },
    /// Internal domain events (legacy — kept for backward compat with 1.1a event loop)
    DomainEvent(DomainEventPayload),

    /// Change the active permission mode.
    SetPermissionMode(PermissionMode),
    /// Retry a message after backoff delay has elapsed.
    RetryMessage {
        conversation_id: ConversationId,
        content: String,
    },
    /// Title generated by background task.
    TitleGenerated {
        conversation_id: ConversationId,
        title: String,
    },
    /// Compaction completed successfully.
    CompactionComplete {
        conversation_id: ConversationId,
        summary: String,
        first_kept_message_id: Option<String>,
        pre_tokens: u32,
        purpose: CompactionPurpose,
    },
    /// Compaction failed.
    CompactionFailed {
        conversation_id: ConversationId,
        reason: String,
        purpose: CompactionPurpose,
    },
    /// AskUserQuestion tool call — display question card and send answer via oneshot.
    AskUserQuestion {
        conversation_id: ConversationId,
        tool_use_id: String,
        question: String,
        response_tx: tokio::sync::oneshot::Sender<String>,
    },
    /// Crash recovery prompt — display recovery FeedbackBlock on startup.
    RecoveryPrompt {
        conversation_id: ConversationId,
        title: String,
        token_count: u32,
    },

    /// Cross-search results ready from an async scan task (Story 4-4 AC5).
    /// Carries the original query so the event loop can discard stale results
    /// if the user has typed more characters in the meantime.
    /// No `conversation_id` — this is a view-update event per Amendment 3.
    CrossSearchResultsReady {
        query: String,
        results: Vec<CrossSearchResult>,
        truncated_by_count: bool,
        truncated_by_time: bool,
    },
    /// Peek highlight for a cross-search jump has expired (Story 4-4 AC6).
    /// Fired 1500 ms after the highlight was set by `OpenCrossSearchResult`.
    /// No `conversation_id` — view-update per Amendment 3. `tab_id` targets
    /// the specific tab whose peek highlight should clear.
    PeekHighlightExpired {
        tab_id: usize,
    },
    /// Skill discovery complete (Story 5-1 AC6).
    SkillsDiscovered {
        count: usize,
        warnings: usize,
    },
    /// Request to activate a skill (Story 5-2 AC8/AC9).
    AskActivateSkill {
        conversation_id: ConversationId,
        name: String,
        arguments: String,
    },
    /// Skill trust prompt for workspace-tier skills (Story 5-2 AC4).
    /// Event loop creates oneshot, TUI displays prompt, user responds y/n/i.
    ///
    /// Contract: consumers awaiting `response_tx` MUST treat `RecvError`
    /// (sender dropped without send — TUI shutdown / panic) as an implicit
    /// `Declined` with an Info-level feedback block, NOT as a silent hang.
    SkillTrustPrompt {
        skill_name: String,
        skill_file: std::path::PathBuf,
        response_tx: tokio::sync::oneshot::Sender<SkillTrustResponse>,
    },
    /// Completes a user-driven skill activation after the user responds to the
    /// trust prompt (Story 5-2 deadlock fix). Emitted by Branch 1's
    /// `SkillTrustAccept`/`SkillTrustDecline` handlers; consumed by Branch 2.
    ///
    /// `trusted: false` means the user declined — Branch 2 emits a decline
    /// notice and does nothing else.
    CompleteSkillActivation {
        conversation_id: ConversationId,
        skill_name: String,
        skill_file: std::path::PathBuf,
        arguments: String,
        trusted: bool,
    },
    AgentsDiscovered {
        count: usize,
        warnings: usize,
    },
    AgentThenSubmit {
        conversation_id: ConversationId,
        text: String,
        synthetic: bool,
    },
    /// Bridge event: a `ToolCallTransition` has been received on the broadcast
    /// channel and should be forwarded to the event loop for TUI/state updates.
    ToolCallTransitionBridged {
        conversation_id: ConversationId,
        transition: crate::domain::models::ToolCallTransition,
    },
    /// Bridge event: an `ApprovalRuntimeEvent` has been received on the broadcast
    /// channel and should be forwarded to the event loop for TUI/state updates.
    ApprovalRuntimeEventBridged {
        event: crate::domain::services::approval_runtime::ApprovalRuntimeEvent,
    },

    /// Story 7.6 AC8 — fired by the discovery background task on successful catalog refresh.
    /// The event-loop handler sets needs_redraw = true.
    ProviderCatalogRefreshed {
        provider_id: String,
    },

    /// Plan mode exit requested — present the plan approval card to the user.
    PlanApprovalRequested {
        conversation_id: ConversationId,
        plan_path: std::path::PathBuf,
        contents: String,
        summary: String,
    },
    /// Plan approval resolved by the user.
    PlanApprovalResolved {
        conversation_id: ConversationId,
        outcome: crate::domain::models::PlanApprovalOutcome,
    },

    PlanProposed {
        conversation_id: ConversationId,
        plan: crate::domain::models::Plan,
    },
    PlanCardResolved {
        conversation_id: ConversationId,
        plan_id: String,
        decision: crate::domain::models::PlanDecision,
    },
    PlanCardEditCompleted {
        conversation_id: ConversationId,
        plan_id: String,
        edited_plan: Option<crate::domain::models::Plan>,
    },
    PlanExecutionStarted {
        conversation_id: ConversationId,
        plan_id: String,
    },
    /// Per-task status update — fired by PlanRuntime on each transition (Pending → Running,
    /// Running → Completed/Failed/Skipped/Cancelled, etc.). Story 6.3's task panel
    /// subscribes to this for real-time render.
    PlanTaskStatusChanged {
        conversation_id: ConversationId,
        plan_id: String,
        task_number: u32,
        status: crate::domain::models::PlanTaskStatus,
    },
    /// All tasks terminal; unified summary has been appended to the conversation.
    PlanCompleted {
        conversation_id: ConversationId,
        plan_id: String,
        completed: u32,
        failed: u32,
        skipped: u32,
        total_elapsed_ms: i64,
    },
    /// Plan execution was interrupted by a Cancelled task (AC2 hard-stop branch).
    /// 6.4 will additionally emit this on user-initiated `!cancel-plan`.
    PlanCancelled {
        conversation_id: ConversationId,
        plan_id: String,
        /// Task that triggered the cancel; None for whole-plan cancel from 6.4 user action.
        cancelled_at_task: Option<u32>,
    },
    /// Story 8.1 AC-10 — emitted by SIGHUP handler, /config reload slash command,
    /// and (in future) `rustain config reload` cross-process IPC. The handler
    /// reloads the layered config chain and atomically swaps the active AppConfig.
    ConfigReload,
    /// Story 8.1 AC-15 — result of a config reload, emitted by the handler after
    /// the reload succeeds or fails. Carries the actual outcome so telemetry
    /// subscribers receive truthful data (not hardcoded success).
    ConfigReloaded {
        success: bool,
        error: Option<String>,
    },
    /// Story 6.4: emitted when the executing plan deviates from the approved plan
    /// (auto-skip of blocked tasks; agent-proposed revision deferred to 6.4-FU1).
    /// TUI renders a PlanDeviationCard requiring reapproval in Normal/Plan modes;
    /// YOLO mode auto-continues with a notice.
    PlanDeviation {
        conversation_id: ConversationId,
        plan_id: String,
        deviation_kind: crate::domain::models::plan::PlanDeviationKind,
        original_step_count: u32,
        current_step_count: u32,
        changed_steps: Vec<u32>,
        summary: String,
    },
}

/// Event wrapping a tool execution result.
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct ToolResultEvent {
    pub result: ToolResult,
}

/// Terminal input events, abstracted from crossterm.
/// The TUI adapter converts `crossterm::event::Event` into these.
#[derive(Debug, Clone)]
pub enum DomainInputEvent {
    KeyPress(char),
    SpecialKey(DomainKey),
    Resize(u16, u16),
    FocusGained,
    FocusLost,
    /// Raw image bytes pasted from clipboard (already decoded from base64 if applicable).
    // Covers: FR112
    ImagePaste(Vec<u8>),
    /// Plain text pasted from clipboard (bracketed paste mode).
    Paste(String),
    /// Mouse scroll event carrying the ScrollDelta payload. Story 16.8, AC4.
    MouseScroll(ScrollDelta),
}

/// Abstract key representation — no crossterm dependency.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DomainKey {
    Enter,
    ShiftEnter,
    CtrlEnter,
    /// Alt+Enter: insert newline (VS Code terminal alternative to Shift+Enter).
    // Covers: Sprint Change Proposal 2026-04-08, UX-DR76 amendment
    AltEnter,
    /// Alt+M: toggle multi-line mode (VS Code terminal alternative to Ctrl+E).
    // Covers: Sprint Change Proposal 2026-04-08, UX-DR76 amendment
    AltM,
    /// Alt+V: paste image (or text) from the system clipboard.
    AltV,
    Esc,
    Backspace,
    Delete,
    Up,
    Down,
    Left,
    Right,
    Home,
    End,
    Tab,
    ShiftTab,
    CtrlB,
    CtrlC,
    CtrlD,
    CtrlE,
    CtrlF,
    CtrlH,
    CtrlK,
    CtrlP,
    CtrlR,
    CtrlT,
    CtrlU,
    CtrlX,
}

/// Purpose of a compaction operation.
#[derive(Debug, Clone)]
pub enum CompactionPurpose {
    Inline,
    Carryover,
    SwitchAfter {
        provider_id: String,
        model_id: String,
    },
}

/// Payload for domain-originated events (placeholder for future stories).
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub enum DomainEventPayload {
    /// Placeholder — streaming events, tool results, etc. added in later stories
    Noop,
}

/// Tool progress event emitted by the bash adapter during long-running execution.
/// Story 16.9 — surfaced via the live rail + stdout tail in the render path.
#[derive(Debug, Clone)]
pub enum ToolProgressEvent {
    Counter { tool_use_id: String, k: u64, n: u64 },
    Tail { tool_use_id: String, text: String },
}

/// Action returned by apply_chunk() to tell the event loop what to do.
#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ChunkAction {
    /// No action needed.
    None,
    /// Trigger a redraw on next tick.
    NeedsRedraw,
    /// Turn is complete — persist and optionally generate title.
    TurnComplete {
        persist: bool,
        trigger_title_generation: bool,
    },
    /// Turn continues (tool use loop).
    TurnContinuing,
}
