//! Integration tests for `rustain completions <shell>` (Story 13.3b, FR104).
//!
//! AC7 guardrail tests: clap debug_assert, derived-set + closure contract (bash),
//! per-shell light checks, --bin-name override, invalid/missing shell rejection,
//! broken-pipe safety, and hidden-subcommand assertion.
//!
//! No `#[serial]` (no env/FS mutation). No `test-instrumentation` gate.

use std::collections::BTreeSet;
#[cfg(unix)]
use std::os::unix::process::ExitStatusExt;

use assert_cmd::Command;
use clap::CommandFactory;
use predicates::prelude::*;
use rustain::adapters::cli::commands::Cli;

fn rustain_cmd() -> Command {
    Command::cargo_bin("rustain").unwrap()
}

/// Derive the expected top-level command set from clap at test time.
/// Filters by the generator's visibility predicate: `!is_hide_set()`.
fn expected_top_level() -> BTreeSet<String> {
    Cli::command()
        .get_subcommands()
        .filter(|c| !c.is_hide_set())
        .map(|c| c.get_name().to_string())
        .collect()
}

/// Extract top-level subcommand names from the bash completion script.
///
/// Bash completions generated by clap_complete use `rustain,<cmd>)` case-arm
/// patterns in the command dispatch loop for top-level subcommands.
fn extract_bash_commands(script: &str) -> BTreeSet<String> {
    let mut cmds = BTreeSet::new();
    // In clap_complete 4.6.x, top-level subcommand dispatch uses case arms like:
    //   `rustain,ask)` → `cmd="rustain__subcmd__ask"`
    // We parse the `rustain,<name>)` patterns (one nesting level only).
    for line in script.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("rustain,") {
            if let Some(cmd) = rest.strip_suffix(')') {
                // Skip `help` (auto-generated by clap, not in our Command enum)
                // and `$1` (the root self-reference pattern).
                if cmd != "help" && !cmd.starts_with('$') {
                    cmds.insert(cmd.to_string());
                }
            }
        }
    }
    cmds
}

// ─── AC7(a): clap debug_assert ─────────────────────────────────────────────

#[test]
fn clap_debug_assert() {
    Cli::command().debug_assert();
}

// ─── AC7(b): Derived-set + closure contract (bash) ─────────────────────────

#[test]
fn bash_completion_command_set_matches_clap() {
    let output = rustain_cmd()
        .args(["completions", "bash"])
        .output()
        .expect("failed to execute");
    assert!(output.status.success(), "exit code != 0");
    let script = String::from_utf8_lossy(&output.stdout);
    assert!(!script.is_empty(), "stdout must not be empty");

    let expected = expected_top_level();
    let actual = extract_bash_commands(&script);

    // Both directions: no missing command, no phantom command.
    let missing: BTreeSet<_> = expected.difference(&actual).collect();
    let phantom: BTreeSet<_> = actual.difference(&expected).collect();

    assert!(
        missing.is_empty(),
        "Commands in clap but NOT in bash script: {missing:?}"
    );
    assert!(
        phantom.is_empty(),
        "Commands in bash script but NOT in clap: {phantom:?}"
    );
    assert_eq!(expected, actual, "command sets must be identical");

    // Anti-vacuous: if clap_complete changes its bash output format and the
    // parser returns an empty set, the symmetric difference would still pass.
    // A non-empty guard forces the parser to actually match something.
    assert!(
        !actual.is_empty(),
        "bash parser found zero top-level commands — clap_complete output format may have changed"
    );
}
// ─── AC7(c): Per-shell light checks (zsh/fish/powershell) ─────────────────

// Structural self-name markers:
//   zsh: `#compdef <bin>`
//   fish: `complete -c <bin>`
//   powershell: `Register-ArgumentCompleter -Native -CommandName '<bin>'`
// These are chosen to avoid false-positives from help text / comments.
#[test]
fn zsh_completion_exit_0_and_contains_self_name() {
    rustain_cmd()
        .args(["completions", "zsh"])
        .assert()
        .success()
        .stdout(predicates::str::is_empty().not())
        .stdout(predicates::str::contains("#compdef rustain"));
}

#[test]
fn fish_completion_exit_0_and_contains_self_name() {
    rustain_cmd()
        .args(["completions", "fish"])
        .assert()
        .success()
        .stdout(predicates::str::is_empty().not())
        .stdout(predicates::str::contains("complete -c rustain"));
}

#[test]
fn powershell_completion_exit_0_and_contains_self_name() {
    rustain_cmd()
        .args(["completions", "powershell"])
        .assert()
        .success()
        .stdout(predicates::str::is_empty().not())
        .stdout(predicates::str::contains(
            "Register-ArgumentCompleter -Native -CommandName 'rustain'",
        ));
}

// ─── AC7(d): --bin-name default and override ───────────────────────────────

#[test]
fn bin_name_default_matches_clap_get_name() {
    let expected_name = Cli::command().get_name().to_string();
    let output = rustain_cmd()
        .args(["completions", "bash"])
        .output()
        .expect("failed to execute");
    assert!(output.status.success());
    let script = String::from_utf8_lossy(&output.stdout);

    // The bash script's function name uses the bin name as the root.
    // Structural marker: `_rustain()` function or `(rustain,` dispatch.
    assert!(
        script.contains(&format!("_{expected_name}()")),
        "default script must contain _{expected_name}() function marker"
    );
}

#[test]
fn bin_name_override_embeds_custom_name() {
    let output = rustain_cmd()
        .args(["completions", "bash", "--bin-name", "acme"])
        .output()
        .expect("failed to execute");
    assert!(output.status.success());
    let script = String::from_utf8_lossy(&output.stdout);

    // Structural marker: `_acme()` function for the custom bin name.
    assert!(
        script.contains("_acme()"),
        "overridden script must contain _acme() function marker"
    );
    // Must NOT contain the default name's root function.
    assert!(
        !script.contains("_rustain()"),
        "overridden script must NOT contain _rustain() function marker"
    );
}

// ─── AC5: Invalid/missing shell rejection ──────────────────────────────────

#[test]
fn invalid_shell_rejected() {
    let output = rustain_cmd()
        .args(["completions", "tcsh"])
        .output()
        .expect("failed to execute");
    assert!(!output.status.success(), "invalid shell must fail");
    assert!(
        output.stdout.is_empty(),
        "invalid shell must produce no stdout"
    );
    assert!(
        !output.stderr.is_empty(),
        "invalid shell must print usage error"
    );
}

#[test]
fn missing_shell_rejected() {
    let output = rustain_cmd()
        .args(["completions"])
        .output()
        .expect("failed to execute");
    assert!(!output.status.success(), "missing shell must fail");
}

#[test]
fn empty_bin_name_uses_default() {
    let output = rustain_cmd()
        .args(["completions", "bash", "--bin-name", ""])
        .output()
        .expect("failed to execute");
    assert!(output.status.success(), "empty --bin-name must succeed");
    let script = String::from_utf8_lossy(&output.stdout);
    assert!(
        script.contains("_rustain()"),
        "empty --bin-name must fall back to default bin name"
    );
}

#[test]
fn invalid_bin_name_rejected() {
    rustain_cmd()
        .args(["completions", "bash", "--bin-name", "foo;bar"])
        .assert()
        .failure()
        .stderr(predicates::str::contains("invalid --bin-name"));
}

// Broken-pipe handling differs by platform (Unix SIGPIPE vs Windows Err(BrokenPipe)).
#[cfg(unix)]
#[test]
fn broken_pipe_exits_cleanly() {
    use std::process::Stdio;
    // Run rustain directly in a pipeline with an early-closing reader so we can
    // inspect rustain's own exit status, not the outer `sh` pipeline's status.
    let bin = assert_cmd::cargo::cargo_bin("rustain");
    let mut rustain = std::process::Command::new(&bin)
        .args(["completions", "bash"])
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("failed to spawn rustain");

    let rustain_stdout = rustain.stdout.take().expect("rustain has no stdout");

    // Attach `head -n1` as the early-closing reader.
    let head = std::process::Command::new("head")
        .arg("-n1")
        .stdin(rustain_stdout)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .output()
        .expect("failed to run head");
    assert!(head.status.success(), "head should exit 0");

    let output = rustain
        .wait_with_output()
        .expect("failed to wait for rustain");
    let stderr = String::from_utf8_lossy(&output.stderr);

    // Rustain must terminate cleanly: no panic text, no "failed printing" message,
    // and a non-error exit. On Unix with SIGPIPE reset to SIG_DFL, a broken pipe
    // terminates the process via signal 13 (exit code 141), which is the expected
    // clean behavior for a CLI tool.
    let clean_exit = output.status.success()
        || output.status.signal() == Some(libc::SIGPIPE)
        || output.status.code().is_none();
    assert!(
        clean_exit,
        "rustain must exit cleanly on broken pipe; got status {:?}, stderr: {stderr}",
        output.status
    );
    assert!(
        !stderr.contains("panic"),
        "broken pipe must not panic; stderr: {stderr}"
    );
    assert!(
        !stderr.contains("failed printing to stdout"),
        "broken pipe must not print 'failed printing to stdout'; stderr: {stderr}"
    );
}

// On Windows there is no SIGPIPE; rustain should return Ok(()) on Err(BrokenPipe).
#[cfg(not(unix))]
#[test]
fn broken_pipe_exits_cleanly() {
    use std::process::Stdio;
    let bin = assert_cmd::cargo::cargo_bin("rustain");
    let mut rustain = std::process::Command::new(&bin)
        .args(["completions", "bash"])
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("failed to spawn rustain");

    let rustain_stdout = rustain.stdout.take().expect("rustain has no stdout");
    let head = std::process::Command::new("powershell")
        .args(["-NoProfile", "-Command", "\u{0026} { process { break } }"])
        .stdin(rustain_stdout)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .output()
        .expect("failed to run head");
    drop(head);

    let output = rustain
        .wait_with_output()
        .expect("failed to wait for rustain");
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        output.status.success(),
        "rustain must exit 0 on broken pipe; got status {:?}, stderr: {stderr}",
        output.status
    );
    assert!(
        !stderr.contains("panic"),
        "broken pipe must not panic; stderr: {stderr}"
    );
    assert!(
        !stderr.contains("failed printing to stdout"),
        "broken pipe must not print 'failed printing to stdout'; stderr: {stderr}"
    );
}

// ─── AC7(g): Hidden-subcommand assertion ───────────────────────────────────

#[test]
fn hidden_subcommand_not_in_completions() {
    // `DaemonAction::__run` is `hide = true` (commands.rs). It must NOT appear
    // as a top-level completion. The daemon sub-subcommands are nested under
    // `daemon`, so `__run` appears as `rustain__daemon__run` if at all — but
    // crucially, `is_hide_set()` means the generator should exclude it.

    let output = rustain_cmd()
        .args(["completions", "bash"])
        .output()
        .expect("failed to execute");
    assert!(output.status.success());
    let script = String::from_utf8_lossy(&output.stdout);

    // The hidden `__run` should not have its own dispatch function in the script.
    // It would appear as `_rustain__daemon____run` or similar pattern if emitted.
    // Verify the expected set from clap does NOT include it:
    let hidden: Vec<_> = Cli::command()
        .get_subcommands()
        .filter(|c| c.is_hide_set())
        .map(|c| c.get_name().to_string())
        .collect();
    // There should be no hidden top-level commands currently.
    assert!(
        hidden.is_empty(),
        "unexpected hidden top-level commands: {hidden:?}"
    );

    // Check the daemon subcommand's hidden child `__run` specifically:
    let cmd = Cli::command();
    let daemon_cmd = cmd
        .get_subcommands()
        .find(|c| c.get_name() == "daemon")
        .expect("daemon subcommand must exist");
    let daemon_hidden: Vec<_> = daemon_cmd
        .get_subcommands()
        .filter(|c| c.is_hide_set())
        .map(|c| c.get_name().to_string())
        .collect();
    assert!(
        daemon_hidden.contains(&"__run".to_string()),
        "daemon __run must be hidden"
    );

    // Verify the bash script does NOT contain the hidden __run as a visible
    // completion option. In clap_complete bash output, hidden subcommands are
    // excluded from the case-arm dispatch.
    assert!(
        !script.contains("(rustain__daemon____run)"),
        "__run must not appear as a visible completion case-arm"
    );
}

// ─── Optional P1: bash -n syntax smoke ──────────────────────────────────────

/// Check whether `program --version` works; if not, print a clear message and
/// skip the syntax check. Using `eprintln!` + early return keeps the test green
/// on machines without the shell installed, while making the skip visible.
fn shell_available(program: &str) -> bool {
    let available = std::process::Command::new(program)
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);
    if !available {
        eprintln!("{program} not available, skipping syntax check");
    }
    available
}

#[test]
fn zsh_syntax_check() {
    if !shell_available("zsh") {
        return;
    }

    let output = rustain_cmd()
        .args(["completions", "zsh"])
        .output()
        .expect("failed to generate zsh completions");
    assert!(output.status.success());

    // `zsh -n` parses the script without executing.
    let syntax_check = std::process::Command::new("zsh")
        .arg("-n")
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .and_then(|mut child| {
            use std::io::Write;
            child
                .stdin
                .take()
                .unwrap()
                .write_all(&output.stdout)
                .unwrap();
            child.wait_with_output()
        })
        .expect("failed to run zsh -n");

    assert!(
        syntax_check.status.success(),
        "zsh -n syntax check failed: {}",
        String::from_utf8_lossy(&syntax_check.stderr)
    );
}

#[test]
fn bash_syntax_check() {
    if !shell_available("bash") {
        return;
    }

    let output = rustain_cmd()
        .args(["completions", "bash"])
        .output()
        .expect("failed to generate bash completions");
    assert!(output.status.success());
    let syntax_check = std::process::Command::new("bash")
        .arg("-n")
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .and_then(|mut child| {
            use std::io::Write;
            child
                .stdin
                .take()
                .unwrap()
                .write_all(&output.stdout)
                .unwrap();
            child.wait_with_output()
        })
        .expect("failed to run bash -n");

    assert!(
        syntax_check.status.success(),
        "bash -n syntax check failed: {}",
        String::from_utf8_lossy(&syntax_check.stderr)
    );
}
